name: macos-latest(arm64) build

on:
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  macos_build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Doit
      run: |
        # which gcc-12
        # which brew
        brew install boost eigen llvm libopenmpt libtiff
        echo "find boost"
        find /opt/homebrew -name "boost" 2>/dev/null
        echo "find llvm"
        find /opt/homebrew -name "llvm" 2>/dev/null
        echo "find Eigen"
        find /opt/homebrew -name "Eigen" 2>/dev/null
        cd Cell2Fire
        echo "cleaning"
        make clean -f makefile.macos-latest
        echo "building"
        make -f makefile.macos-latest
        echo "end build"
        ldd Cell2Fire
        ext=`python3 -c "import platform;print(f'.{platform.system()}.{platform.machine()}')"`
        echo "extension $ext"
        mv Cell2Fire Cell2Fire$ext

    - name: Test
      run: |
        cd test
        bash test.sh

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binaries-Darwin-arm64
        path: Cell2Fire/Cell2Fire.Darwin.arm64
