name: build and release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Doit
      run: |
        sudo apt install g++-12 libboost-all-dev libeigen3-dev
        cd Cell2FireC
        make clean -f makefile.ubuntu-latest
        make -f makefile.ubuntu-latest
        ext=`python3 -c "import platform;print(f'.{platform.system()}.{platform.machine()}')"`
        mv Cell2Fire Cell2Fire$ext
        ls Cell2Fire*

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: Cell2FireC/Cell2Fire.Linux.x86_64

  macos_build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Doit
      run: |
        # which gcc-12
        # which brew
        brew install boost eigen llvm libopenmpt
        # find /usr/local -name "Eigen" 2>/dev/null
        # find /usr/local -name "boost" 2>/dev/null
        # find /usr/local -name "llvm" 2>/dev/null
        cd Cell2FireC
        make clean -f makefile.macos-latest
        make -f makefile.macos-latest
        ext=`python3 -c "import platform;print(f'.{platform.system()}.{platform.machine()}')"`
        mv Cell2Fire Cell2Fire$ext
        ls Cell2Fire*

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: Cell2FireC/Cell2Fire.Darwin.x86_64

  windows_build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: call workflow file
      uses: .github/workflows/buildwindows.yml

  release:
    needs: [ubuntu_build, macos_build, windows_build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download
      uses: actions/download-artifact@v3

    - name: Doit
      run: |
        git archive --prefix=C2F/Cell2FireC/ \
          --add-file=binaries/Cell2Fire.Linux.x86_64 \
          --add-file=binaries/Cell2Fire.Darwin.x86_64 \
          --add-file=binaries/Cell2Fire.exe \
          --prefix=C2F/ \
          --output="Cell2FireW_${{ github.ref_name }}.zip" HEAD

    - name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "Cell2FireW_${{ github.ref_name }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
