name: build macos all

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        runner: ["macos-12", "macos-13", "macos-14"]
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

    - name: Check Runner
      run: |
        arch
        echo "runner: ${{ matrix.runner }}.$(arch).$(uname -m)"
        brew config

    - name: Install Dependencies
      run: |
        brew install gcc@12 eigen # libomp boost libtiff llvm 

    - name: Build
      run: |
        cd Cell2Fire
        make clean
        make -f makefile.macos-all
        otool -L Cell2Fire > otool_${{ matrix.runner }}.txt
        mv Cell2Fire Cell2Fire_${{ matrix.runner }}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binaries_${{ matrix.runner }}
        path: |
          Cell2Fire/otool_${{ matrix.runner }}.txt
          Cell2Fire/Cell2Fire_${{ matrix.runner }}
