name: build macos all

on:
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        runner: ["macOS-12", "macOS-13", "macOS-14"]
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Check Runner
      run: |
        echo "suffix="$(uname -s).${{ matrix.runner }}.$(arch)"" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        brew install libomp eigen boost libtiff # llvm ?

    - name: Build
      continue-on-error: true
      run: |
        cd Cell2Fire
        make clean
        make -f makefile.macos-test
        otool -L Cell2Fire > otool_${{ env.suffix }}.txt
        mv Cell2Fire Cell2Fire_${{ env.suffix }}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binaries_${{ env.suffix }}
        path: |
          Cell2Fire/otool_${{ env.suffix }}.txt
          Cell2Fire/Cell2Fire_${{ env.suffix }}

