name: ubuntu build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache apt packages
      uses: actions/cache@v3
      with:
        path: /usr/local/lib
        key: ${{ runner.os }}-apt-${{ hashFiles('**/Cell2Fire/**') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++-12 libboost-all-dev libeigen3-dev libtiff-dev

    - name: Build
      run: |
        cd Cell2Fire
        # attempt to add libtiff.so to binaries lib
        mkdir lib
        # Find libtiff.so and check if it exists
        afile=$(find /usr -name "libtiff.so" 2>/dev/null)
        if [ -f "$afile" ]; then
          # Copy the file only if it exists
          cp "$afile" "lib/"
        else
          echo "libtiff.so not found in /usr"
        fi
        ls lib
        # build
        make clean -f makefile.ubuntu-latest
        make -f makefile.ubuntu-latest
        ldd Cell2Fire
        ext=`python3 -c "import platform;print(f'.{platform.system()}.{platform.machine()}')"`
        mv Cell2Fire Cell2Fire$ext
        # ls Cell2Fire*

    - name: Test
      run: |
        cd test
        bash test.sh

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binaries-Linux-x86_64
        path: Cell2Fire/Cell2Fire.Linux.x86_64
