name: macos build

on:
  # push:
  #   branches:
  #     - buildwindows
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  macos_build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Doit
      run: |
        # which gcc-12
        # which brew
        brew install boost eigen llvm libopenmpt
        echo "find 0"
        find /usr/local -name "Eigen"
        echo "find 1"
        # find /usr/local -name "boost" 2>/dev/null
        # find /usr/local -name "llvm" 2>/dev/null
        cd Cell2Fire
        make clean -f makefile.macos-latest
        make -f makefile.macos-latest
        ext=`python3 -c "import platform;print(f'.{platform.system()}.{platform.machine()}')"`
        mv Cell2Fire Cell2Fire$ext
        # ls Cell2Fire*

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: Cell2Fire/Cell2Fire.Darwin.x86_64
