name: build macos all

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        runner: ["macos-12", "macos-13", "macos-14"]
    runs-on: ${{ matrix.runner }}

    steps:
      # - name: Checkout Code
      #   uses: actions/checkout@v4

    - name: Check Runner
      run: |
        arch
        echo "runner: ${{ matrix.runner }}.$(arch).$(uname -m)"
        brew config

    - name: Install Dependencies
      run: |
        brew install gcc@12 eigen # libomp boost libtiff llvm 

    - name: Build
      run: |
        cd Cell2Fire
        make clean
        make -f makefile.macos-all
        otool -L Cell2Fire > otool_${{ matrix.runner }}.txt
        mv Cell2Fire Cell2Fire_${{ matrix.runner }}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binaries_${{ matrix.runner }}
        path: |
          Cell2Fire/otool_${{ matrix.runner }}.txt
          Cell2Fire/Cell2Fire_${{ matrix.runner }}

        #test:
        #needs: build
        #runs-on: macos-12

        #steps:
        #- name: Checkout Code
        #  uses: actions/checkout@v4

        #- name: Install Dependencies
        #  if: false
        #  run: |
        #    apt update
        #    apt install -y lsb-release unzip libtiff6 libgomp1
        #    # apt install -y g++-12 make lsb-release unzip libboost-all-dev libeigen3-dev libtiff-dev

        #- name: Get Environment
        #  if: false
        #  id: get_env
        #  run: |
        #    DISTRIBUTION=$( lsb_release --short --id 2>/dev/null )
        #    CODENAME=$( lsb_release --short --codename 2>/dev/null )
        #    MACHINE=$( uname --machine 2>/dev/null )
        #    echo "SUFFIX=".${DISTRIBUTION}.${CODENAME}.${MACHINE}"" >> $GITHUB_ENV

        #- name: Download Artifacts
        #  uses: actions/download-artifact@v4
        #  with:
        #    pattern: binaries
        #    path: Cell2Fire
        #    merge-multiple: true

        #- name: chmod
        #  run: |
        #    ls Cell2Fire
        #    chmod +x Cell2Fire/Cell2Fire

        #- name: Test
        #  run: |
        #    cd test
        #    bash test.sh
