name: build manylinux

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y g++-12 libboost-all-dev libeigen3-dev libtiff-dev libjpeg-dev libjbig-dev liblzma-dev libzstd-dev libwebp-dev libdeflate-dev libleptonica-dev liblerc-dev

    - name: Check Packages Versions
      run: |
        dpkg-query -W -f='${binary:Package} ${Version}\n' g++-12 libboost-all-dev libeigen3-dev libtiff-dev libjpeg-dev libjbig-dev liblzma-dev libzstd-dev libwebp-dev libdeflate-dev libleptonica-dev liblerc-dev > new_pkgs_ubuntu.txt
        cat new_pkgs_ubuntu.txt
        # if [ -n "$(diff new_pkgs_ubuntu.txt pkgs_ubuntu.txt)" ]; then
        #   echo "::warning:: apt packages versions diff! $(diff new_pkgs_ubuntu.txt pkgs_ubuntu.txt)"
        #   diff_output=$(diff --side-by-side --suppress-common-lines new_pkgs_ubuntu.txt pkgs_ubuntu.txt || true)
        #   echo "$diff_output" | while IFS= read -r line; do
        #     echo "$line"
        #   done
        # fi

    - name: Get Environment
      id: get_env
      run: |
        DISTRIBUTION=$( lsb_release --short --id 2>/dev/null )
        CODENAME=$( lsb_release --short --codename 2>/dev/null )
        MACHINE=$( uname --machine 2>/dev/null )
        echo "SUFFIX=".${DISTRIBUTION}.${CODENAME}.${MACHINE}"" >> $GITHUB_ENV

    - name: Build
      # continue-on-error: true
      run: |
        cd Cell2Fire
        make clean
        make 
        mkdir ~/binaries
        ldd Cell2Fire > ~/binaries/ldd.txt
        mv Cell2Fire ~/binaries/Cell2Fire${{ env.SUFFIX }}
        make clean
        capture_warn=$(make -f makefile.static 2>&1 >> ~/binaries/ldd.txt)
        ldd Cell2Fire >> ~/binaries/ldd.txt
        mv Cell2Fire ~/binaries

    - name: Test
      run: |
        cd test
        bash test.sh

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: binaries

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: binaries
        path: Cell2Fire

    - name: TestManyLinux
      run: |
        cd test
        bash test.sh

    - name: TestSuffix
      run: |
        cd test
        bash test.sh ${{ env.SUFFIX }}
