name: windows build

on:
  # push:
  #   branches:
  #     - buildwindows
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  windows_build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: download dependencies
      run: |
        echo "Hello"
        cd Cell2Fire
        mkdir include

        # dirent
        Invoke-WebRequest -Uri https://github.com/tronkko/dirent/archive/refs/tags/1.24.zip -OutFile dirent-1.24.zip
        Expand-Archive -Path .\dirent-1.24.zip -DestinationPath include

        # eigen
        $project_id = 15462818
        $commit_sha = "776d86d8df175b7036467a0ef131bd34755f847d"
        $path = "Eigen"
        $url = "https://gitlab.com/api/v4/projects/$project_id/repository/archive?sha=$commit_sha&path=$path"
        Invoke-WebRequest -Uri $url -OutFile eigen.tar.gz
        tar -xzf eigen.tar.gz
        mv eigen-$commit_sha-$commit_sha-Eigen include\eigen3

        # boost
        $fname = "boost_1_84_0.tar.gz"
        Invoke-WebRequest -Uri https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/$fname -OutFile $fname
        tar -xzf $fname -C include

    - name: vcpkg build
      uses: johnwason/vcpkg-action@v6
      id: vcpkg
      with:
        pkgs: tiff
        triplet: x64-windows-release
        token: ${{ github.token }}
        github-binarycache: true


    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Build Solution
      run: |
        # local using powershell
        # & "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe" Cell2Fire.sln /p:Configuration=Release
        dir
        dir .\vcpkg
        dir .\vcpkg\installed
        dir .\vcpkg\installed\x64-windows-release
        dir .\vcpkg\installed\x64-windows-release\include
        cd Cell2Fire
        msbuild Cell2Fire.sln /p:Configuration=Debug

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: Cell2Fire/x64/Release/Cell2Fire.exe

