name: ubuntu build

on:
  # push:
  #   branches:
  #     - buildwindows
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        sudo apt install g++-12 libboost-all-dev libeigen3-dev
        cd Cell2Fire
        make clean -f makefile.ubuntu-latest
        make -f makefile.ubuntu-latest
        ext=`python3 -c "import platform;print(f'.{platform.system()}.{platform.machine()}')"`
        mv Cell2Fire Cell2Fire$ext
        # ls Cell2Fire*

        # - name: Test
        #   run: |
        #     cd test
        #     bash test.sh

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binaries-Linux-x86_64
        path: Cell2Fire/Cell2Fire.Linux.x86_64
