name: debian stable build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  debian_build:
    runs-on: ubuntu-latest
    container: debian:stable-slim

    steps:
    - name: Install dependencies
      run: |
        apt update
        apt install -y g++-12 make lsb-release libboost-all-dev libeigen3-dev libtiff-dev

    - name: Get Environment
      id: get_env
      run: |
        echo `DISTRIBUTION=$( lsb_release --short --id 2>/dev/null )`
        echo `CODENAME=$( lsb_release --short --codename 2>/dev/null )`
        echo `MACHINE=$( uname --machine 2>/dev/null )`
        echo 'SUFFIX=".$DISTRIBUTION.$CODENAME.$MACHINE"' >> $GITHUB_ENV
        
        # - name: Stop
        #   run: throw "Exiting!"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: |
        cd Cell2Fire
        make clean
        make
        ldd Cell2Fire
        mv Cell2Fire Cell2Fire${{ env.SUFFIX }}

        # - name: Test
        #   run: |
        #     cd test
        #     bash test.sh ${{ env.SUFFIX }}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binaries.${{ env.SUFFIX }}
        path: Cell2Fire/Cell2Fire${{ env.SUFFIX }}
