name: ubuntu build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  ubuntu_build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++-12 libboost-all-dev libeigen3-dev libtiff-dev
        dpkg-query -W -f='${binary:Package} ${Version}\n' g++-12 libboost-all-dev libeigen3-dev libtiff-dev > new_apt_versions.txt
        if [ -n "$(diff new_apt_versions.txt apt_versions.txt)" ]; then
          echo "::warning:: apt packages versions diff: $(diff new_apt_versions.txt apt_versions.txt)"
          diff --side-by-side --suppress-common-lines new_apt_versions.txt apt_versions.txt 2>/dev/null
        fi

    - name: Get Environment
      id: get_env
      run: |
        echo "DISTRIBUTION=$( lsb_release --short --id 2>/dev/null )" >> $GITHUB_ENV
        echo "CODENAME=$( lsb_release --short --codename 2>/dev/null )" >> $GITHUB_ENV
        echo "MACHINE=$( uname --machine 2>/dev/null )" >> $GITHUB_ENV
        echo "A ${{ env.CODENAME }},${{ env.MACHINE }},${{ env.DISTRIBUTION }}"
        echo "B $CODENAME,$MACHINE,$DISTRIBUTION"
        # - name: Stop
        #   run: throw "Exiting!"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: |
        cd Cell2Fire
        make clean
        make
        ldd Cell2Fire
        mv Cell2Fire Cell2Fire.${{ env.DISTRIBUTION }}.${{ env.CODENAME }}.${{ env.MACHINE }}

    - name: Test
      run: |
        cd test
        bash test.sh .${{ env.DISTRIBUTION }}.${{ env.CODENAME }}.${{ env.MACHINE }}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ env.DISTRIBUTION }}-${{ env.CODENAME }}-${{ env.MACHINE }}
        path: Cell2Fire/Cell2Fire.${{ env.DISTRIBUTION }}.${{ env.CODENAME }}.${{ env.MACHINE }}
