name: build and release
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-\w+'

permissions:
  contents: write

jobs:
  call_ubuntu_build:
      uses: ./.github/workflows/buildubuntu-latest.yml

  # call_macos_build:
  #     uses: ./.github/workflows/buildmacos-latest.yml

  # call_macos_build_13:
  #     uses: ./.github/workflows/buildmacos-13.yml

  call_windows_build:
      uses: ./.github/workflows/buildwindows.yml

  release:
    # needs: [call_ubuntu_build, call_macos_build, call_macos_build_13, call_windows_build]
    needs: [call_ubuntu_build, call_windows_build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: binaries-*
        path: binaries
          # merge-multiple: true

    - name: ZipDataInstances
      run: |
        cd data
        zip -r ../Kitral.zip Kitral
        zip -r ../CanadianFBP.zip CanadianFBP
        zip -r ../ScottAndBurgan.zip ScottAndBurgan  

    - name: WindowsZip
      run: |
        cd binaries/binaries-Windows-x86_64
        dir
        zip ../../Cell2Fire_win64_standalone.zip Cell2Fire.exe *.dll
        git rm *.dll Cell2Fire.pdb Cell2Fire.ilk

    - name: GitArchive
      run: |
        git rm -r data output test
        git archive --prefix=C2F/Cell2Fire/ \
          --add-file=binaries/binaries-Linux-x86_64/Cell2Fire.Linux.x86_64 \
          --add-file=binaries/binaries-Windows-x86_64/Cell2Fire.exe \
          --prefix=C2F/ \
          --output="Cell2FireW_${{ github.ref_name }}.zip" HEAD
          # --add-file=binaries/Cell2Fire.Darwin.arm64 \
          # --add-file=binaries/Cell2Fire.Darwin.x86_64 \

    - name: Create Draft Release for PR
      if: github.event_name == 'pull_request'
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "Cell2FireW_${{ github.sha }}.zip,Kitral.zip,CanadianFBP.zip,ScottAndBurgan.zip,Cell2Fire_win64_standalone.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        tag: ${{ github.sha }}
        name: "Draft Release for PR #${{ github.event.pull_request.number }}"
        body: "This is a draft release for pull request #${{ github.event.pull_request.number }}."

    - name: Create Release for Tag
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "Cell2FireW_${{ github.ref_name }}.zip,Kitral.zip,CanadianFBP.zip,ScottAndBurgan.zip,Cell2Fire_win64_standalone.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        tag: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        body: "This is the release for tag ${{ github.ref_name }}."

