name: debian stable build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:stable-slim

    - name: Install dependencies
      run: |
        apt-get update
        sudo apt install -y g++-12 make libboost-all-dev libeigen3-dev libtiff-dev

    steps:
    - name: Get Environment
      id: get_env
      run: |
        echo "DISTRIBUTION=$( lsb_release --short --id 2>/dev/null )" >> $GITHUB_ENV
        echo "CODENAME=$( lsb_release --short --codename 2>/dev/null )" >> $GITHUB_ENV
        echo "MACHINE=$( uname --machine 2>/dev/null )" >> $GITHUB_ENV
        echo ${{ env.CODENAME }},${{ env.MACHINE }},${{ env.DISTRIBUTION }}
        echo ${{ env }}
        # - name: Stop
        #   run: throw "Exiting!"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        cd Cell2Fire
        make clean
        make
        ldd Cell2Fire
        mv Cell2Fire Cell2Fire.${{ env.DISTRIBUTION }}.${{ env.CODENAME }}.${{ env.MACHINE }}
        #- name: Test
        #  run: |
        #    cd test
        #    bash test.sh

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ env.DISTRIBUTION }}-${{ env.CODENAME }}-${{ env.MACHINE }}
        path: Cell2Fire/Cell2Fire.${{ env.DISTRIBUTION }}.${{ env.CODENAME }}.${{ env.MACHINE }}
