name: build and release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-\w+'

permissions:
  contents: write

jobs:
  call_ubuntu_build:
      uses: ./.github/workflows/buildubuntu-latest.yml

  call_macos_build:
      uses: ./.github/workflows/buildmacos-latest.yml

  call_macos_build_13:
      uses: ./.github/workflows/buildmacos-13.yml

  call_windows_build:
      uses: ./.github/workflows/buildwindows.yml

  release:
    needs: [call_ubuntu_build, call_macos_build, call_macos_build_13, call_windows_build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download
      uses: actions/download-artifact@v4

    - name: GitArchive
      run: |
        git archive --prefix=C2F/Cell2Fire/ \
          --add-file=binaries/Cell2Fire.Linux.x86_64 \
          --add-file=binaries/Cell2Fire.Darwin.x86_64 \
          --add-file=binaries/Cell2Fire.Darwin.arm64 \
          --add-file=binaries/Cell2Fire.exe \
          --prefix=C2F/ \
          --output="Cell2FireW_${{ github.ref_name }}.zip" HEAD

    - name: ZipDataInstances
      run: |
        cd data
        zip -r ../Kitral.zip Kitral
        zip -r ../CanadianFBP.zip CanadianFBP
        zip -r ../ScottAndBurgan.zip ScottAndBurgan  

    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "Cell2FireW_${{ github.ref_name }}.zip,Kitral.zip,CanadianFBP.zip,ScottAndBurgan.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
