name: build and release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Doit
      run: |
        sudo apt install g++-12 libboost-all-dev libeigen3-dev
        cd Cell2FireC
        make clean
        make -f makefile.ubuntu-latest
        echo "fin make"
        mv Cell2Fire Cell2Fire.linux
        ls Cell2*
        echo "fin"
        # cd ..

    - name: Upload
    - uses: actions/upload-artifact@v3
      with:
        name: linux
        path: Cell2FireC/Cell2Fire.linux

  macos_build:
    needs: ubuntu_build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Doit
      run: |
        # which brew
        # which gcc-12
        brew install boost eigen llvm libopenmpt
        # find /usr/local -name "Eigen" 2>/dev/null
        # find /usr/local -name "boost" 2>/dev/null
        # find /usr/local -name "llvm" 2>/dev/null
        cd Cell2FireC
        make clean
        make -f makefile.macos-latest
        echo "fin make"
        mv Cell2Fire Cell2Fire.macos_arm
        ls Cell2*
        echo "fin"
        # cd ..

    - name: Upload
    - uses: actions/upload-artifact@v3
      with:
        name: linux
        path: Cell2FireC/Cell2Fire.linux

  release:
    needs: [ubuntu_build, macos_build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        path: Cell2FireC

    - name: Doit
      run: |
        ls Cell2FireC
        git add Cell2FireC/Cell2Fire.linux Cell2FireC/Cell2Fire.macos_arm
        git archive --prefix=C2F/ --output="Cell2FireW_${{ github.ref_name }}.zip" HEAD

    - name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "Cell2FireW_${{ github.ref_name }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
