name: macos-13(x86_64) build

on:
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  macos_build:
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Brew Packages
      run: |
        brew update
        brew install gcc@12
        brew install boost eigen llvm libomp libtiff

    - name: Describe & Find Packages
      run: |
        echo "arch"
        arch
        g++-12 --version
        echo "find boost"
        find /opt/homebrew -name "boost" 2>/dev/null
        echo "find llvm"
        find /opt/homebrew -name "llvm" 2>/dev/null
        echo "find Eigen"
        find /opt/homebrew -name "Eigen" 2>/dev/null
        packages=("gcc" "boost" "eigen" "llvm" "libomp" "libtiff")
        for package in "${packages[@]}"; do
          version=$(brew info --json=v1 "$package" | jq -r '.[0].installed[0].version')
          if [[ -n "$version" ]]; then
            echo "$package $version"
          fi
        done

    - name: Build
      run: |
        cd Cell2Fire
        echo "clean"
        make clean -f makefile.macos-13
        echo "build"
        make -f makefile.macos-13
        echo "linkage"
        otool -L Cell2Fire
        echo "rename"
        ext=`python3 -c "import platform;print(f'.{platform.system()}.{platform.machine()}')"`
        echo "extension $ext"
        mv Cell2Fire Cell2Fire$ext

    - name: Test
      run: |
        cd test
        bash test.sh

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binaries-Darwin-x86_64
        path: Cell2Fire/Cell2Fire.Darwin.x86_64
