name: windows build

on:
  workflow_dispatch:
  push:
    branches:
      - buildwindows

permissions:
  contents: write

jobs:
  windows_build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache Boost and Eigen packages
      uses: actions/cache@v2
      with:
        path: C:\ProgramData\chocolatey\packages
        key: ${{ runner.os }}-boost-eigen-${{ hashFiles('Cell2Fire.sln') }}
        restore-keys: ${{ runner.os }}-boost-eigen-

    - name: Install Boost and Eigen packages (if not cached)
      uses: actions/cache@v2
      env:
        CHOCOLATEY_CACHE_LOCATION: C:\ProgramData\chocolatey\packages
        run: choco install boost-msvc-12 eigen

    - name: Set platform system machine
      shell: cmd
      run: |
        echo "Hello World!"
        echo %PATH%
        echo cd
        echo "suffix=$(python3 -c 'import platform;print(platform.system()+"."+platform.machine())')" >> $GITHUB_ENV
        choco install dirent
        type C:\ProgramData\chocolatey\logs\chocolatey.log
        REM git clone https://gitlab.com/libeigen/eigen
        # https://github.com/tronkko/dirent

    - name: Compile Visual Studio project with MSBuild
      working-directory: Cell2FireC
      shell: cmd
      run: |
        where msbuild
        ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && msbuild' }}
        REM    cd Cell2FireC
        msbuild Cell2Fire.sln
        echo "Bye World!!"

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: Cell2FireC/Cell2Fire.exe

