name: windows build

on:
  pull_request:
    branches:
      - main
        # workflow_dispatch:
        # workflow_call:

permissions:
  contents: write

jobs:
  windows_build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: |
          vcpkg
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Cache Boost
      id: cache-boost
      uses: actions/cache@v4
      with:
        path: |
          Cell2Fire/include/boost_1_84_0
        key: boost-${{ runner.os }}-1.84.0
        restore-keys: |
          boost-${{ runner.os }}-

    - name: Cache Eigen
      id: cache-eigen
      uses: actions/cache@v4
      with:
        path: |
          Cell2Fire/include/eigen3
        key: eigen-${{ runner.os }}-776d86d8df175b7036467a0ef131bd34755f847d
        restore-keys: |
          eigen-${{ runner.os }}-

    - name: Cache Dirent
      id: cache-dirent
      uses: actions/cache@v4
      with:
        path: |
          Cell2Fire/include/dirent-1.24
        key: dirent-${{ runner.os }}-1.24
        restore-keys: |
          dirent-${{ runner.os }}-

    - name: Download dependencies
      if: steps.cache-vcpkg.outputs.cache-hit != 'true' || steps.cache-boost.outputs.cache-hit != 'true' || steps.cache-eigen.outputs.cache-hit != 'true' || steps.cache-dirent.outputs.cache-hit != 'true'
      run: |
        cd Cell2Fire
        New-Item -ItemType Directory -Path "include" -Force

        # dirent
        if (${{ steps.cache-dirent.outputs.cache-hit }} -ne 'true') {
          Invoke-WebRequest -Uri https://github.com/tronkko/dirent/archive/refs/tags/1.24.zip -OutFile dirent-1.24.zip
          Expand-Archive -Path .\dirent-1.24.zip -DestinationPath include
        }

        # eigen
        if (${{ steps.cache-eigen.outputs.cache-hit }} -ne 'true') {
          $project_id = 15462818
          $commit_sha = "776d86d8df175b7036467a0ef131bd34755f847d"
          $path = "Eigen"
          $url = "https://gitlab.com/api/v4/projects/$project_id/repository/archive?sha=$commit_sha&path=$path"
          Invoke-WebRequest -Uri $url -OutFile eigen.tar.gz
          tar -xzf eigen.tar.gz
          mv eigen-$commit_sha-$commit_sha-Eigen include\eigen3
        }

        # boost
        if (${{ steps.cache-boost.outputs.cache-hit }} -ne 'true') {
          $fname = "boost_1_84_0.tar.gz"
          Invoke-WebRequest -Uri https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/$fname -OutFile $fname
          tar -xzf $fname -C include
        }

        # tiffio
        if (${{ steps.cache-vcpkg.outputs.cache-hit }} -ne 'true') {
          git clone https://github.com/microsoft/vcpkg.git vcpkg
        }

    - name: Setup vcpkg
      run: |
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install
        .\vcpkg install tiff

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: |
        cd Cell2Fire
        msbuild Cell2Fire.sln /p:Configuration=Release
      
    - name: Gather output
      run: |
        mkdir binaries
        copy Cell2Fire\include\vcpkg\installed\x64-windows\lib\*.dll binaries
        copy Cell2Fire\x64\Release\Cell2Fire.exe binaries

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binaries-Windows-x86_64
        path: binaries
