name: macos build

on:
  # push:
  #   branches:
  #     - buildwindows
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  macos_build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Doit
      run: |
        # which gcc-12
        # which brew
        brew install boost eigen llvm libopenmpt libtiff
        find /opt/homebrew -name "boost" 2>/dev/null
        find /opt/homebrew -name "llvm" 2>/dev/null
        find /opt/homebrew -name "Eigen" 2>/dev/null
        find /opt/homebrew -name "tiffio.h" 2>/dev/null
        cd Cell2Fire
        make clean -f makefile.macos-latest
        make -f makefile.macos-latest
        ext=`python3 -c "import platform;print(f'.{platform.system()}.{platform.machine()}')"`
        mv Cell2Fire Cell2Fire$ext
        # ls Cell2Fire*

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: Cell2Fire/Cell2Fire.Darwin.arm64
