name: macos build

on:
  # push:
  #   branches:
  #     - buildwindows
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  macos_build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Doit
      run: |
        # which gcc-12
        # which brew
        brew install boost eigen llvm libopenmpt
        echo "find boost"
        find /opt/homebrew -name "boost" 2>/dev/null
        echo "find llvm"
        find /opt/homebrew -name "llvm" 2>/dev/null
        echo "find Eigen"
        find /opt/homebrew -name "Eigen" 2>/dev/null
        cd Cell2Fire
        echo "cleaning"
        make clean -f makefile.macos-latest
        echo "building"
        make -f makefile.macos-latest
        echo "end build"
        ls Cell2Fire*
        ext=`python3 -c "import platform;print(f'.{platform.system()}.{platform.machine()}')"`
        echo "extension $ext"
        mv Cell2Fire Cell2Fire$ext
        ls Cell2Fire*

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: Cell2Fire/Cell2Fire.Darwin.arm64
