name: windows build

on:
  push:
    branches:
      - buildwindows
  workflow_dispatch:

permissions:
  contents: write

jobs:
  windows_build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create Chocolatey package cache directory
      run: mkdir C:\ProgramData\chocolatey\packages

    - name: Cache Boost and Eigen packages
      uses: actions/cache@v3
      id: cache-choco
      with:
        path: C:\ProgramData\chocolatey\packages
        key: ${{ runner.os }}-boost-eigen-${{ hashFiles('C:\ProgramData\chocolatey\packages') }}
        restore-keys: ${{ runner.os }}-boost-eigen-

    - name: Install Boost and Eigen packages (if not cached)
      uses: crazy-max/ghaction-chocolatey@v3
      if: steps.cache-choco.outputs.cache-hit != 'true'
      env:
        CHOCOLATEY_CACHE_LOCATION: C:\ProgramData\chocolatey\packages
      with:
        args: install -v boost-msvc-14.3 eigen
      # choco install eigen --version v3.4.0
      # boost 1.58.0
      # https://community.chocolatey.org/packages/eigen#files
      # https://community.chocolatey.org/packages/boost-msvc-14.3#files

    - name: get dirent release
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "tronkko/dirent"
        latest: true
        zipBall: true
        tarBall: false

    - name: check choco
      run: |
        echo "Hello"
        # pwd D:\a\C2F-W\C2F-W
        # dir 
        mkdir Cell2FireC\include
        Expand-Archive -Path .\dirent-1.24.zip -DestinationPath Cell2FireC\include
        New-Item -ItemType SymbolicLink -Path .\Cell2FireC\include\eigen -Target C:\ProgramData\chocolatey\lib\eigen\include
        New-Item -ItemType SymbolicLink -Path .\Cell2FireC\include\boost-msvc-12 -Target C:\ProgramData\chocolatey\lib\boost-msvc-14.3
        dir C:\ProgramData\chocolatey\lib\boost-msvc-14.3
        echo "Bye"

        # - name: Set platform system machine
        #   shell: cmd
        #   run: |
        #     echo "Hello World!"
        #     dir Cell2FireC
        #     dir Cell2FireC\include\tronkko-dirent-a3aeddf
        #     REM echo %PATH%
        #     REM echo %cd%
        #     REM echo "suffix=$(python3 -c 'import platform;print(platform.system()+"."+platform.machine())')" >> $GITHUB_ENV
        #     echo `python3 -c 'import platform;print(platform.system()+"."+platform.machine())')`
        #     dir C:\ProgramData\chocolatey\packages

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Build solution
      run: |
        cd Cell2FireC
        msbuild Cell2Fire.sln

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: Cell2FireC/x64/Release/Cell2Fire.exe

