name: Delete all caches

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete all caches
        uses: actions/cache@v2
        with:
          restore-keys: []
