name: Example Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_var: ${{ steps.step1.outputs.my_var }}
    steps:
      - name: Step 1
        id: step1
        run: echo "my_var=Hello World" >> $GITHUB_ENV

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use variable from job1
        run: echo "The variable from job1 is: ${{ needs.job1.outputs.my_var }}"

