name: test matrix
on:
  push:
  workflow_dispatch:

jobs:
  matrix:
    name: "Build: ${{ matrix.config.arch }}"
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        config:
          - { arch: 'ARM64'}
          - { arch: 'x86_64'}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        run: |
          echo "${{ matrix.config.arch }}"
          echo $(arch)
          arch -"${{ matrix.config.arch }}" echo $(uname -v) $(uname -m)
          arch -"${{ matrix.config.arch }}" g++ -o hello hello.cpp
          file -b hello 
