name: test matrix
on:
  push:
  workflow_dispatch:

jobs:
  matrix:
    name: "Build: ${{ matrix.config.name }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        os: macos-latest
        arch: ['arm64', 'x86_64']
    steps:
      - name: Get color
        run: |
          echo "${{ matrix.os }} - ${{ matrix.arch }}"
          echo $(arch)
          echo $(uname -v)
