name: test matrix
on:
  push:
  workflow_dispatch:

jobs:
  matrix:
    name: "Build: ${{ matrix.config.arch }}"
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        config:
          - { arch: 'arm64'}
          - { arch: 'x86_64'}
    steps:
      - name: Get color
        run: |
          echo "${{ matrix.config.arch }}"
          echo $(arch)
          echo $(uname -v) $(uname -m)
